### ISSUE TITLE
Twitch Login Doesn't Reset Between Auths

### ISSUE THREAD

**Issue by Tons0fun** [Skhmt/koalabot2#1]
When you authorize the streamer account and then click on the button to authorize the bot account, it attempts to use the streamer Twitch account rather than asking the user to log in again. The user must select the "Not you?" link in order to authorize their bot account.

**Comment by Skhmt** [comment]
I'm aware of this, it has to do with nw.js caching logins. I haven't looked too much in to fixing it, as I think it's more of a help (people who want to use just one account for both the bot and broadcaster don't have to re-enter their username/password) than a hinderance (one additional click one time during setup for people who use different accounts).

But idk, maybe no one uses one account for both? Thoughts?

**Comment by Tons0fun** [comment]
I'm sure some people do use one account for both, but I personally would advise against it. Most streamers I know have at least one other account for their bots. And having multiple Twitch accounts isn't against ToS unless it is for ban evading or something along those lines.

I'm sure there are plenty who use their main account for both, so it might be a good opportunity to educate maybe?

**Comment by Skhmt** [comment]
Hm. It's always an interesting argument on enforcing good practices vs enabling users to do anything.

Also I don't even know if I can fix the issue, lol.
